"""add material_type_id to callout_associations

Revision ID: 693db3dbc8c7
Revises: 
Create Date: 2026-03-29 00:22:44.564132

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693db3dbc8c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('callout_associations', sa.Column('material_type_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'callout_associations', 'material_types', ['material_type_id'], ['material_type_id'])
    op.add_column('callouts', sa.Column('nearby_texts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('callouts', 'nearby_texts')
    op.drop_constraint(None, 'callout_associations', type_='foreignkey')
    op.drop_column('callout_associations', 'material_type_id')
    # ### end Alembic commands ###
